name-template: 'v$NEXT_PATCH_VERSION 🚀'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: 🚀 New Features
    labels:
      - feature
  - title: 🐛 Bug Fixes
    labels:
      - bug
  - title: 🛠️ Maintenance
    labels:
      - chore
change-template: '- ${{PR.title}} (#${{PR.number}})'
template: |
  ## What's Changed
  $CHANGES
