name: Build Windows OpenIPC Config Avalonia App  
on:
  # manual runs
  workflow_dispatch:
  push:
    branches:
      - test-actions
      
jobs:
  build:
    name: Build and Package for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        include:
          - os: windows-latest
            arch: x64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.404'
          
      - name: Install Android and iOS workloads
        run: |
          dotnet workload install android
          dotnet workload install wasi-experimental

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet publish -c Release -r win-x64 --self-contained

      - name: List output directory
        run: dir bin\Release\net8.0\win-x64\publish

      - name: Install rcedit
        run: choco install rcedit

      - name: Set Windows Icon
        run: |
          rcedit "bin\Release\net8.0\win-x64\publish\OpenIPC-Config.exe" --set-icon "Assets\OpenIPC.ico"
        shell: cmd

      - name: Zip Windows App
        run: |
          mkdir dist
          Compress-Archive -Path "bin\Release\net8.0\win-x64\publish\*" -DestinationPath "dist\OpenIPC-Config-windows-x64.zip"
        shell: pwsh

      - name: Upload Windows App Artifact
        uses: actions/upload-artifact@v3
        with:
          name: OpenIPC-Config-windows-x64
          path: dist\OpenIPC-Config-windows-x64.zip
