name: Debug Secrets

permissions:
  contents: write
  actions: read
      
on:
  workflow_dispatch:
  

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        arch: [arm64]
        # os: [ubuntu-latest]
        # arch: [arm64]


    steps:
      - name: Debug Secrets
        env:
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
        run: |
          if [[ -z "$APPLE_CERTIFICATE" ]]; then
            echo "APPLE_CERTIFICATE is not set or empty."
          else
            echo "APPLE_CERTIFICATE is set."
          fi
      
          if [[ -z "$APPLE_CERTIFICATE_PASSWORD" ]]; then
            echo "APPLE_CERTIFICATE_PASSWORD is not set or empty."
          else
            echo "APPLE_CERTIFICATE_PASSWORD is set."
          fi
